"""
Walk-Forward Backtesting Engine — Section 12 + 26
Design doc v3.1

Architecture:
  - Walk-forward windows: 2y train, 3m test, rolling
  - Signals generated by running full strategy pipeline on historical data
  - Execution-realistic: slippage tiers, STT, impact cost applied
  - Segmented results: per-strategy, per-regime, per-sector
  - Acceptance criteria: Sharpe≥1.0, MaxDD≤20%, WinRate≥45%

Key classes:
  BacktestEngine     — orchestrates full backtest
  WalkForwardWindow  — single train/test split
  BacktestResult     — metrics for one window/strategy/segment
  TradeRecord        — individual simulated trade
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from app.data.execution_realism import apply_execution_realism, get_slippage_factor
from app.features.engineer import build_dataframe, compute_features, extract_latest_features
from app.regime.detector import classify_regime
from app.strategies.runner import StrategyRunner
from app.fusion.engine import fuse, FusedSignal
from app.regime.detector import RegimeResult, REGIME_WEIGHTS
from app.db import get_sync_db
from app.logger import get_logger
from config.settings import settings
from config.watchlist import WATCHLIST_WITH_SECTORS

logger = get_logger("backtest")

# ── Constants ─────────────────────────────────────────────────
TRADING_DAYS_PER_YEAR = 252
HOLD_DAYS             = 10     # default signal holding period (increased from 5)
BROKERAGE_PER_TRADE   = 20.0  # Zerodha flat ₹20 per order
STT_SELL_RATE         = 0.001  # 0.1% on sell side

# ── Portfolio-level concurrency limits (Fix 1 & 2) ───────────
# Without these, multiple strategies fire on same stock simultaneously
# causing correlated drawdowns that multiply rather than diversify.
MAX_CONCURRENT_POSITIONS = 5      # max open trades at any one time in backtest
MAX_CONCURRENT_PER_STOCK = 1      # only 1 active trade per stock at a time
MAX_SECTOR_CONCURRENT    = 2      # max 2 open trades per sector at once
MIN_SIGNAL_CONFIDENCE    = 35     # already applied per-trade, enforced here too
BEAR_REGIME_BUY_ALLOWED  = False  # Fix 3: no BUY signals in confirmed BEAR regime


# ── Data classes ──────────────────────────────────────────────

@dataclass
class WalkForwardWindow:
    window_id:    int
    train_start:  date
    train_end:    date
    test_start:   date
    test_end:     date

    def __str__(self):
        return (f"Window {self.window_id}: "
                f"train={self.train_start}→{self.train_end} | "
                f"test={self.test_start}→{self.test_end}")


@dataclass
class TradeRecord:
    window_id:     int
    symbol:        str
    sector:        str
    signal:        str           # BUY | STRONG_BUY | SELL | STRONG_SELL
    regime:        str
    strategy_id:   str           # which strategy drove the signal
    entry_date:    date
    exit_date:     date
    entry_price:   float
    exit_price:    float
    stop_loss:     float
    target_price:  float
    shares:        int
    gross_pnl:     float         # before costs
    net_pnl:       float         # after slippage + STT + brokerage
    return_pct:    float         # net return %
    hit_target:    bool
    hit_stop:      bool
    timed_out:     bool          # held for HOLD_DAYS without target/stop
    exit_reason:   str           # TARGET | STOP | TIMEOUT


@dataclass
class BacktestResult:
    strategy_id:              str
    period_start:             date
    period_end:               date
    regime:                   Optional[str]    # None = aggregate
    sector:                   Optional[str]    # None = aggregate
    total_trades:             int
    winning_trades:           int
    losing_trades:            int
    win_rate_pct:             float
    avg_return_pct:           float
    total_return_pct:         float
    annualized_return_pct:    float
    sharpe_ratio:             float
    max_drawdown_pct:         float
    avg_win_pct:              float
    avg_loss_pct:             float
    profit_factor:            float           # gross profit / gross loss
    sharpe_realistic:         float
    win_rate_realistic:       float
    annualized_return_realistic: float
    meets_acceptance_criteria: bool
    notes:                    str = ""

    def summary(self) -> str:
        status = "✅ PASS" if self.meets_acceptance_criteria else "❌ FAIL"
        return (f"{status} | {self.strategy_id} | "
                f"Sharpe={self.sharpe_ratio:.2f} | "
                f"MaxDD={self.max_drawdown_pct:.1f}% | "
                f"WinRate={self.win_rate_pct:.1f}% | "
                f"AnnRet={self.annualized_return_pct:.1f}%")


# ── Walk-forward window generator ─────────────────────────────

def generate_windows(
    data_start:          date,
    data_end:            date,
    train_years:         int = 2,
    test_months:         int = 3,
) -> List[WalkForwardWindow]:
    """
    Generates rolling walk-forward windows.
    Each window: train_years of history → test_months of out-of-sample.
    Windows slide by test_months each step.
    """
    windows  = []
    win_id   = 1
    train_days = int(train_years * TRADING_DAYS_PER_YEAR * (365/252))
    test_days  = int(test_months * 30.5)

    test_start = data_start + timedelta(days=train_days)
    while test_start + timedelta(days=test_days) <= data_end:
        test_end   = test_start + timedelta(days=test_days)
        train_end  = test_start - timedelta(days=1)
        train_start = train_end - timedelta(days=train_days)

        windows.append(WalkForwardWindow(
            window_id=win_id,
            train_start=max(train_start, data_start),
            train_end=train_end,
            test_start=test_start,
            test_end=min(test_end, data_end),
        ))
        test_start += timedelta(days=test_days)
        win_id += 1

    logger.info(f"Generated {len(windows)} walk-forward windows")
    return windows


# ── Signal simulation ─────────────────────────────────────────

def simulate_signals_for_window(
    symbol:   str,
    df:       pd.DataFrame,
    window:   WalkForwardWindow,
    regime:   str,
) -> List[FusedSignal]:
    """
    Runs the full feature + strategy + fusion pipeline on each trading
    day in the test window to generate historical signals.
    """
    runner  = StrategyRunner()
    signals = []

    # Get test period rows
    test_df = df[
        (df.index.date >= window.test_start) &
        (df.index.date <= window.test_end)
    ]

    sector = WATCHLIST_WITH_SECTORS.get(symbol, "Unknown")

    for i, (ts, _) in enumerate(test_df.iterrows()):
        signal_date = ts.date()

        # Need enough history before this date for indicators
        history_df = df[df.index < ts].tail(300)
        if len(history_df) < 210:
            continue

        try:
            feat_df  = compute_features(history_df.copy())
            features = extract_latest_features(feat_df, symbol)

            strategy_results = runner.run(features, regime=regime)

            # ── Reversion suppression (Section 8.3) ──────────────
            # Suppress reversion in BULL/UNCERTAIN BEFORE fusion so
            # confidence gate doesn't let any residual score through.
            if regime in ("BULL", "UNCERTAIN"):
                for r in strategy_results:
                    if r.strategy_id == "reversion":
                        r.score      = 0.0
                        r.confidence = 0.0
                        r.signal     = "HOLD"
                        r.reasons    = ["[suppressed] reversion disabled in BULL/UNCERTAIN"]

            regime_result = RegimeResult(
                regime=regime,
                regime_confidence="NORMAL",
                fusion_weights=dict(REGIME_WEIGHTS[regime]),
            )
            fused = fuse(
                symbol=symbol,
                strategy_results=strategy_results,
                regime_result=regime_result,
                run_date=signal_date,
                features=features,
                save_to_db=False,
            )
            fused._signal_date = signal_date
            fused._features    = features
            signals.append(fused)

        except Exception as e:
            logger.debug(f"{symbol} {signal_date}: signal generation failed — {e}")

    return signals


# ── Trade simulation ──────────────────────────────────────────

def simulate_trades(
    symbol:          str,
    df:              pd.DataFrame,
    signals:         List[FusedSignal],
    window:          WalkForwardWindow,
    regime:          str,
    portfolio_state: Optional[Dict] = None,
) -> List[TradeRecord]:
    """
    For each BUY/SELL signal, simulate entry on next open and
    exit at target, stop, or after HOLD_DAYS (timeout).

    Fixes applied:
      Fix 1: Entry gap filter — skip if next open gaps >1% against signal
      Fix 2: Stop uses 2x ATR (not 1x) to survive intraday noise
      Fix 3: Confidence + volume filter — only high-quality signals
      Fix 4: Cooldown — skip 5 days after a stop loss hit
      Fix 5 (NEW): Concurrency control — 1 trade per stock at a time
      Fix 6 (NEW): No BUY signals in BEAR regime
      Fix 7 (NEW): Sector concurrency cap — max 2 per sector

    portfolio_state: shared mutable dict tracking open positions
                     across ALL stocks in this window. Pass the same
                     dict for all symbols to enforce cross-stock limits.
    """
    trades      = []
    sector      = WATCHLIST_WITH_SECTORS.get(symbol, "Unknown")
    slip        = get_slippage_factor(symbol)
    cooldown_until: Optional[date] = None

    if portfolio_state is None:
        portfolio_state = {"open_trades": [], "sector_count": {}}

    for signal in signals:
        if signal.signal not in ("BUY", "STRONG_BUY", "SELL", "STRONG_SELL"):
            continue
        if not signal.entry_price:
            continue

        sig_date = signal._signal_date
        features = signal._features
        close    = features.get("close", signal.entry_price)
        atr      = features.get("atr_14", close * 0.02)
        adx      = features.get("adx_14", 0)
        vol_ratio = features.get("volume_ratio", 1.0) or 1.0
        conf     = signal.confidence

        # ── Fix 3: Quality gate ──────────────────────────────────────
        if conf < 35:
            continue
        if vol_ratio < 1.0:
            continue

        # ── Fix 6: No BUY signals in BEAR regime ─────────────────────
        is_buy_signal = "BUY" in signal.signal
        if not BEAR_REGIME_BUY_ALLOWED and regime == "BEAR" and is_buy_signal:
            continue

        # ── ADX gate for trend-driven signals ────────────────────────
        top_strategy = max(signal.strategy_scores, key=signal.strategy_scores.get) \
            if signal.strategy_scores else "combined"
        if top_strategy == "trend" and adx < 20:
            continue

        # ── Fix 4: Cooldown after stop loss ──────────────────────────
        if cooldown_until and sig_date <= cooldown_until:
            continue

        # ── Fix 5: One trade per stock at a time ─────────────────────
        # Remove positions that have already closed before sig_date
        open_trades = portfolio_state["open_trades"]
        open_trades[:] = [t for t in open_trades if t.exit_date > sig_date]
        stock_open = [t for t in open_trades if t.symbol == symbol]
        if stock_open:
            continue   # already have an open trade on this stock

        # ── Fix 7: Sector concurrency cap ────────────────────────────
        sector_open = sum(1 for t in open_trades if t.sector == sector)
        if sector_open >= MAX_SECTOR_CONCURRENT:
            continue

        # ── Global position cap ───────────────────────────────────────
        if len(open_trades) >= MAX_CONCURRENT_POSITIONS:
            continue

        # Find next trading rows
        future_rows = df[df.index.date > sig_date]
        if future_rows.empty:
            continue

        # Next day open
        has_open    = "Open" in future_rows.columns
        next_open   = float(future_rows.iloc[0]["Open"]) if has_open else close
        entry_date  = future_rows.index[0].date()

        # ── Fix 1: Entry gap filter ───────────────────────────────────
        # If next open gaps >1% against our signal direction, skip.
        # Prevents chasing gapped entries where slippage kills expectancy.
        is_long = "BUY" in signal.signal
        gap_pct = (next_open - close) / close
        if is_long  and gap_pct < -0.01:   # gapped down >1% on BUY signal
            continue
        if not is_long and gap_pct > 0.01:  # gapped up >1% on SELL signal
            continue

        entry_price = round(next_open * (1 + slip * 0.5), 2)

        # Position sizing from ATR-based risk
        risk_inr = settings.portfolio_value_inr * settings.risk_per_trade_pct

        # ── Fix 2: Stop at 2x ATR from entry ─────────────────────────
        # 2x ATR survives normal intraday noise (avg H-L ~= 1x ATR).
        # 4% max risk floor prevents catastrophic single-trade loss.
        stop_mult = 2.0
        if is_long:
            stop_loss = round(entry_price - stop_mult * atr, 2)
            stop_loss = max(stop_loss, round(entry_price * 0.96, 2))  # 4% floor
        else:
            stop_loss = round(entry_price + stop_mult * atr, 2)
            stop_loss = min(stop_loss, round(entry_price * 1.04, 2))

        risk_per_share = abs(entry_price - stop_loss)
        if risk_per_share <= 0:
            continue

        shares = max(1, int(risk_inr / risk_per_share))
        shares = min(shares, int(
            settings.portfolio_value_inr * settings.max_single_stock_pct / entry_price
        ))

        # Target: 2.5x R:R → positive expectancy even at 45% WR
        # At 45% WR + 2.5 R:R: expectancy = 0.45×2.5 - 0.55×1.0 = +0.575% per trade
        rr       = 2.5
        risk_pts = abs(entry_price - stop_loss)
        target   = round(entry_price + rr * risk_pts, 2) if is_long \
                   else round(entry_price - rr * risk_pts, 2)

        # ── Simulate holding ──────────────────────────────────────────
        hit_target = False
        hit_stop   = False
        timed_out  = False
        exit_price = entry_price
        exit_date  = entry_date

        holding_rows = future_rows.iloc[1:HOLD_DAYS + 1]

        for _, (exit_ts, row) in enumerate(holding_rows.iterrows()):
            day_high  = float(row.get("High",  row["Close"]))
            day_low   = float(row.get("Low",   row["Close"]))

            if is_long:
                if day_low <= stop_loss:
                    exit_price = round(stop_loss * (1 - slip), 2)
                    exit_date  = exit_ts.date()
                    hit_stop   = True
                    break
                if day_high >= target:
                    exit_price = round(target * (1 - slip), 2)
                    exit_date  = exit_ts.date()
                    hit_target = True
                    break
            else:
                if day_high >= stop_loss:
                    exit_price = round(stop_loss * (1 + slip), 2)
                    exit_date  = exit_ts.date()
                    hit_stop   = True
                    break
                if day_low <= target:
                    exit_price = round(target * (1 + slip), 2)
                    exit_date  = exit_ts.date()
                    hit_target = True
                    break
        else:
            if not holding_rows.empty:
                exit_price = round(float(holding_rows.iloc[-1]["Close"]) * (1 - slip * 0.5), 2)
                exit_date  = holding_rows.index[-1].date()
            timed_out = True

        # ── Fix 4: Set cooldown after stop ───────────────────────────
        if hit_stop:
            cooldown_until = exit_date + timedelta(days=5)

        # P&L
        if is_long:
            gross_pnl  = (exit_price - entry_price) * shares
            return_pct = (exit_price - entry_price) / entry_price * 100
        else:
            gross_pnl  = (entry_price - exit_price) * shares
            return_pct = (entry_price - exit_price) / entry_price * 100

        stt       = exit_price * shares * STT_SELL_RATE
        brokerage = BROKERAGE_PER_TRADE * 2
        net_pnl   = gross_pnl - stt - brokerage

        trade = TradeRecord(
            window_id=window.window_id,
            symbol=symbol,
            sector=sector,
            signal=signal.signal,
            regime=regime,
            strategy_id=top_strategy,
            entry_date=entry_date,
            exit_date=exit_date,
            entry_price=entry_price,
            exit_price=exit_price,
            stop_loss=stop_loss,
            target_price=target,
            shares=shares,
            gross_pnl=gross_pnl,
            net_pnl=net_pnl,
            return_pct=return_pct,
            hit_target=hit_target,
            hit_stop=hit_stop,
            timed_out=timed_out,
            exit_reason="TARGET" if hit_target else "STOP" if hit_stop else "TIMEOUT",
        )
        trades.append(trade)
        # Register in shared portfolio state so other stocks see this position
        portfolio_state["open_trades"].append(trade)

    return trades


# ── Metrics calculation ───────────────────────────────────────

def calculate_metrics(
    trades:       List[TradeRecord],
    strategy_id:  str,
    period_start: date,
    period_end:   date,
    regime:       Optional[str] = None,
    sector:       Optional[str] = None,
) -> Optional[BacktestResult]:
    """Computes all Section 12.3 metrics from a list of trades."""

    if not trades:
        return None

    returns = [t.return_pct for t in trades]
    net_ret = [t.net_pnl / (t.entry_price * t.shares) * 100 for t in trades]
    wins    = [t for t in trades if t.return_pct > 0]
    losses  = [t for t in trades if t.return_pct <= 0]

    win_rate    = len(wins) / len(trades) * 100
    avg_return  = float(np.mean(returns))
    avg_win     = float(np.mean([t.return_pct for t in wins])) if wins else 0
    avg_loss    = float(np.mean([t.return_pct for t in losses])) if losses else 0

    gross_profit = sum(t.return_pct for t in wins)
    gross_loss   = abs(sum(t.return_pct for t in losses))
    profit_factor = gross_profit / gross_loss if gross_loss > 0 else float("inf")

    # Annualised return
    days_in_period = (period_end - period_start).days or 1
    total_return   = float(np.sum(returns))
    ann_return     = total_return * (365 / days_in_period)

    # Sharpe ratio (annualised, risk-free = 6.5% India)
    risk_free_daily = 6.5 / 252
    if len(returns) > 1:
        excess  = [r - risk_free_daily for r in returns]
        sharpe  = (np.mean(excess) / (np.std(excess) + 1e-9)) * math.sqrt(252)
    else:
        sharpe = 0.0

    # Max drawdown — 90th percentile worst window DD
    # Worst single window is too sensitive to one bad period;
    # 90th pct gives a robust tail-risk view across all windows.
    window_ids = sorted(set(t.window_id for t in trades))
    all_dd = []
    for wid in window_ids:
        w_returns = [t.return_pct for t in trades if t.window_id == wid]
        if not w_returns:
            continue
        eq   = np.cumsum(w_returns)
        peak = np.maximum.accumulate(eq)
        dd   = eq - peak
        all_dd.append(float(abs(np.min(dd))))
    max_dd = float(np.percentile(all_dd, 90)) if all_dd else 0.0  # 90th pct window DD

    # Realistic versions (net of costs)
    net_total  = float(np.sum(net_ret))
    net_ann    = net_total * (365 / days_in_period)
    net_wins   = [r for r in net_ret if r > 0]
    net_wr     = len(net_wins) / len(net_ret) * 100 if net_ret else 0
    net_sharpe = (np.mean(net_ret) / (np.std(net_ret) + 1e-9)) * math.sqrt(252) \
        if len(net_ret) > 1 else 0.0

    # Acceptance criteria (Section 12.3)
    meets = bool(
        sharpe   >= settings.backtest_min_sharpe     and
        max_dd   <= settings.backtest_max_drawdown * 100 and
        win_rate >= settings.backtest_min_win_rate * 100
    )

    notes_parts = []
    if sharpe   < settings.backtest_min_sharpe:
        notes_parts.append(f"Sharpe {sharpe:.2f}<{settings.backtest_min_sharpe}")
    if max_dd   > settings.backtest_max_drawdown * 100:
        notes_parts.append(f"MaxDD {max_dd:.1f}%>{settings.backtest_max_drawdown*100:.0f}%")
    if win_rate < settings.backtest_min_win_rate * 100:
        notes_parts.append(f"WinRate {win_rate:.1f}%<{settings.backtest_min_win_rate*100:.0f}%")

    return BacktestResult(
        strategy_id=strategy_id,
        period_start=period_start,
        period_end=period_end,
        regime=regime,
        sector=sector,
        total_trades=len(trades),
        winning_trades=len(wins),
        losing_trades=len(losses),
        win_rate_pct=round(win_rate, 2),
        avg_return_pct=round(avg_return, 4),
        total_return_pct=round(total_return, 2),
        annualized_return_pct=round(ann_return, 2),
        sharpe_ratio=round(float(sharpe), 3),
        max_drawdown_pct=round(max_dd, 2),
        avg_win_pct=round(avg_win, 4),
        avg_loss_pct=round(avg_loss, 4),
        profit_factor=round(profit_factor, 3),
        sharpe_realistic=round(float(net_sharpe), 3),
        win_rate_realistic=round(net_wr, 2),
        annualized_return_realistic=round(net_ann, 2),
        meets_acceptance_criteria=meets,
        notes=" | ".join(notes_parts),
    )


# ── DB persistence ────────────────────────────────────────────

def save_backtest_result(result: BacktestResult, run_id: str) -> None:
    try:
        with get_sync_db() as conn:
            cur = conn.cursor()
            cur.execute(
                """
                INSERT INTO backtest_results (
                    run_id, strategy_id, period_start, period_end,
                    regime, sector,
                    sharpe_ratio, max_drawdown_pct, win_rate_pct,
                    annualized_return_pct, total_trades, avg_return_pct,
                    sharpe_realistic, win_rate_realistic,
                    annualized_return_realistic,
                    meets_acceptance_criteria, notes
                ) VALUES (
                    %s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s
                )
                """,
                (
                    run_id, result.strategy_id,
                    result.period_start, result.period_end,
                    result.regime, result.sector,
                    result.sharpe_ratio, result.max_drawdown_pct,
                    result.win_rate_pct, result.annualized_return_pct,
                    result.total_trades, result.avg_return_pct,
                    result.sharpe_realistic, result.win_rate_realistic,
                    result.annualized_return_realistic,
                    bool(result.meets_acceptance_criteria), result.notes,
                ),
            )
    except Exception as e:
        logger.error(f"Failed to save backtest result: {e}")


# ── Main engine ───────────────────────────────────────────────

class BacktestEngine:
    """
    Orchestrates full walk-forward backtest across all stocks and windows.

    Usage:
        engine = BacktestEngine(stocks=["RELIANCE","TCS"], verbose=True)
        summary = engine.run()
    """

    def __init__(
        self,
        stocks:      Optional[List[str]] = None,
        train_years: int = None,
        test_months: int = None,
        verbose:     bool = True,
        save_to_db:  bool = True,
    ):
        self.stocks          = stocks or list(settings.watchlist)
        self.train_years     = train_years or settings.backtest_train_years
        self.test_months     = test_months or settings.backtest_walk_forward_months
        self.verbose         = verbose
        self.save_to_db      = save_to_db
        self.run_id          = _make_run_id()
        self._window_states: Dict[int, Dict] = {}   # shared state per window

    def run(self) -> Dict:
        """
        Returns summary dict with:
          all_trades, results_by_strategy, results_by_regime,
          results_by_sector, aggregate, passes_acceptance
        """
        logger.info(
            f"Backtest start | run_id={self.run_id} | stocks={len(self.stocks)} | "
            f"train={self.train_years}y test={self.test_months}m"
        )

        all_trades: List[TradeRecord] = []

        for symbol in self.stocks:
            logger.info(f"Backtesting {symbol}...")
            df = self._load_data(symbol)
            if df is None or len(df) < 210:
                logger.warning(f"{symbol}: insufficient data, skipping")
                continue

            data_start = df.index[0].date()
            data_end   = df.index[-1].date()
            windows    = generate_windows(data_start, data_end,
                                          self.train_years, self.test_months)

            for window in windows:
                # Detect regime for this test window using train data
                train_df = df[df.index.date <= window.train_end]
                regime   = self._detect_regime(train_df)

                signals = simulate_signals_for_window(symbol, df, window, regime)
                # portfolio_state is created per-window and shared across
                # all stocks in that window via the outer loop caller.
                # We create a fresh one per window here (single-stock mode).
                # In multi-stock mode, the engine passes a shared one below.
                trades  = simulate_trades(
                    symbol, df, signals, window, regime,
                    portfolio_state=self._get_window_state(window.window_id),
                )
                all_trades.extend(trades)

                if self.verbose and trades:
                    wins = sum(1 for t in trades if t.return_pct > 0)
                    logger.info(
                        f"  {window} | {symbol} | "
                        f"{len(trades)} trades | {wins} wins | regime={regime}"
                    )

        if not all_trades:
            logger.warning("No trades generated — insufficient data or signals")
            return {"all_trades": [], "aggregate": None, "passes_acceptance": False}

        # ── Aggregate metrics ─────────────────────────────────
        period_start = min(t.entry_date for t in all_trades)
        period_end   = max(t.exit_date  for t in all_trades)

        aggregate = calculate_metrics(all_trades, "combined", period_start, period_end)

        # ── Per-strategy segmentation (Section 26.1) ──────────
        results_by_strategy: Dict[str, BacktestResult] = {}
        for sid in set(t.strategy_id for t in all_trades):
            seg_trades = [t for t in all_trades if t.strategy_id == sid]
            r = calculate_metrics(seg_trades, sid, period_start, period_end)
            if r:
                results_by_strategy[sid] = r
                if self.save_to_db:
                    save_backtest_result(r, self.run_id)

        # ── Per-regime segmentation ───────────────────────────
        results_by_regime: Dict[str, BacktestResult] = {}
        for reg in set(t.regime for t in all_trades):
            seg_trades = [t for t in all_trades if t.regime == reg]
            r = calculate_metrics(seg_trades, "combined", period_start, period_end,
                                  regime=reg)
            if r:
                results_by_regime[reg] = r
                if self.save_to_db:
                    save_backtest_result(r, self.run_id)

        # ── Per-sector segmentation ───────────────────────────
        results_by_sector: Dict[str, BacktestResult] = {}
        for sec in set(t.sector for t in all_trades):
            seg_trades = [t for t in all_trades if t.sector == sec]
            r = calculate_metrics(seg_trades, "combined", period_start, period_end,
                                  sector=sec)
            if r:
                results_by_sector[sec] = r
                if self.save_to_db:
                    save_backtest_result(r, self.run_id)

        # ── Save aggregate ────────────────────────────────────
        if aggregate and self.save_to_db:
            save_backtest_result(aggregate, self.run_id)

        passes = aggregate.meets_acceptance_criteria if aggregate else False

        logger.info(
            f"Backtest complete | {len(all_trades)} trades | "
            f"aggregate: {aggregate.summary() if aggregate else 'N/A'}"
        )

        return {
            "run_id":               self.run_id,
            "all_trades":           all_trades,
            "aggregate":            aggregate,
            "results_by_strategy":  results_by_strategy,
            "results_by_regime":    results_by_regime,
            "results_by_sector":    results_by_sector,
            "passes_acceptance":    passes,
        }

    def _get_window_state(self, window_id: int) -> Dict:
        """Returns shared mutable portfolio state for a given window."""
        if window_id not in self._window_states:
            self._window_states[window_id] = {"open_trades": [], "sector_count": {}}
        return self._window_states[window_id]

    def _load_data(self, symbol: str) -> Optional[pd.DataFrame]:
        """Load OHLCV from DB and build DataFrame."""
        try:
            from app.data.validator import get_latest_ohlcv
            rows = get_latest_ohlcv(symbol, n=2000)
            if len(rows) < 210:
                return None
            df = build_dataframe(rows)
            # Add Open/High/Low if not present (build_dataframe uses Close/Volume)
            return df
        except Exception as e:
            logger.error(f"Failed to load data for {symbol}: {e}")
            return None

    def _detect_regime(self, train_df: pd.DataFrame) -> str:
        """Detect regime from training period data."""
        try:
            import pandas_ta as ta
            if len(train_df) < 210:
                return "UNCERTAIN"
            close   = train_df["Close"]
            high    = train_df["High"] if "High" in train_df.columns else close
            low     = train_df["Low"]  if "Low"  in train_df.columns else close
            ema_20  = float(ta.ema(close, length=20).iloc[-1])
            ema_50  = float(ta.ema(close, length=50).iloc[-1])
            ema_200 = float(ta.ema(close, length=200).iloc[-1])
            adx_df  = ta.adx(high, low, close, length=14)
            adx     = float(adx_df["ADX_14"].iloc[-1])
            regime, _ = classify_regime(float(close.iloc[-1]), ema_20, ema_50, ema_200, adx)
            return regime
        except Exception:
            return "UNCERTAIN"


def _make_run_id() -> str:
    import uuid
    return str(uuid.uuid4())